additionalPrometheusRulesMap:
 custom-rules:
  groups:
  - name: GroupA
    rules:
    - alert: InstanceLowMemory
      expr: :node_memory_MemAvailable_bytes:sum < 50668858390
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Instance memory low"
        description: "less than 50G memory available"
    - alert: InstanceDown
      expr: up == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Instance down"
        description: "job has been down for more than 1 minute."