apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dev
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: backendport-dev
  labels:
    name: backend-dev
    release: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-dev
  template:
    metadata:
      labels:
        app: backend-dev
    spec:
      containers:
        - name: backend-dev
          image: toanla1306/project-3-backend-monitoring:latest
          imagePullPolicy: Always
          ports:
          - name: backendport-dev
            containerPort: 8080
            protocol: TCP
      restartPolicy: Always
      imagePullSecrets:
      - name: secretdockerhub
---
apiVersion: v1
kind: Service
metadata:
  name: backend-dev
  labels:
    app: backend-dev
spec:
  selector:
    app: backend-dev
  ports:
    - name: backend-dev
      protocol: TCP
      port: 8081
      targetPort: backendport-dev
  type: LoadBalancer