apiVersion: v1
kind: Service
metadata:
  name: thanos-sidecar
  namespace: monitoring
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: prometheus-install-kube-pr-prometheus
  ports:
  - port: 10901
    targetPort: grpc